lms/protected/controllers/AppController.php
<?php

class AppController extends Controller
{

	// PRIVATE!! Used only in this controller! Must match  ERP>>BackupSubscription model constants!
	private static $CYCLE_MONTHLY = 'monthly';
	private static $CYCLE_YEARLY = 'yearly';

	/**
	 * Apps on sale with no visible price & activate only by Sales
	 * @var array
	 */
	private $contactUsApps = array('OfflinePlayer', 'Okta', 'SimpleSaml', 'Salesforce', 'AuditTrail');

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}


	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$res = array();


		// keep it in the following order:

		$res[] = array(
			'allow',
			'roles' => array(Yii::app()->user->level_godadmin),
			'expression' => 'BrandingWhiteLabelForm::isMenuVisible()'
		);

		$res[] = array(
			'deny', // deny all
			'users' => array('*'),
			'deniedCallback' => array($this, 'accessDeniedCallback'),
		);

		return $res;
	}


	public function actionActivate()
	{
		PluginManager::loadPlugin('TwitterApp');
		echo TwitterApp::plugin()->activate();
	}


	public function actionIndexOLD()
	{
		$this->render('index_old');
	}

	public function actionIndex(){
	    
	    // Comment this block of code and will get the OLD behavior completely!
	    $api = new ErpApiClient2();
	    $isBundledPricing = $api->call('lms/is-bundle-pricing');
	    if ($isBundledPricing) {
	       $this->forward("apps2/index", true);
	       Yii::app()->end();
	    }
	    
		Yii::app()->clientScript->registerScriptFile(Yii::app()->theme->baseUrl.'/js/myapps-search.js');
		$isInTrialPeriod = Docebo::isTrialPeriod();
		$this->render('index', array(
			'isInTrialPeriod' => $isInTrialPeriod
		));
	}

	public function actionTestlang() {
		$lang = Yii::app()->getLanguage();
		var_dump($lang);
	}

	public function actionTestapi1() {
		$params = array(
			'installation_id' => Docebo::getErpInstallationId(),
			'filter' => 'all' // all|free|paid|my_apps
		);
		$response = AppsMpApiClient::apiListAvailableApps($params);
		echo($response);
		exit;
	}

	public function actionTestapi2() {
		$params = array(
			'installation_id' => Docebo::getErpInstallationId(),
			'app_id' => Yii::app()->request->getParam('id', 9)
		);

		$response = AppsMpApiClient::apiGetAppDetails($params);
		echo($response);
		exit;
	}


	public function actionTestapi3() {
		$appId = Yii::app()->request->getParam('id');

		$app = $this->_getAppDetails($appId);

		var_dump($app);
		var_dump(Docebo::isTrialPeriod());
		exit;
	}

	/**
	 * Get all apps and filter them to use in Search Engine of Apps Page
	 *
	 * @throws CException
	 */
	public function actionGetAllApps(){
		$apps  = $this->_getAllApps();
		$appsData = array();
		$lang = Yii::app()->getLanguage();

		//Fall back to engish if the language is not en or it!!
		switch($lang){
			case 'en':
			case 'it':
				break;
			default:
				$lang = 'en';
				break;
		}
		$isECSInstallation = PluginManager::isPluginActive('EcsApp');

		foreach($apps as $key => $app){
			$isFree = ($app['market_type'] === 'free' ? true : false);
			$appsData[] = array(
				'app_id' => $app['app_id'],
				'name' => $app['lang'][$lang]['title'],
				'description' => $app['lang'][$lang]['short_description'],
				'isFree' => $isFree,
				'body' => $this->renderPartial('_app_template', array(
					'app' => $app,
					'isECSInstallation' => $isECSInstallation
				), true),
				'app' => $app,
				'isECSInstallation' => $isECSInstallation
			);
		}

		echo CJSON::encode(array(
				'html'  => $appsData,
		));
		Yii::app()->end();
	}

	public function actionAxAppsGrid()
	{
		$html = '';

		/*
		 * Call the erp api to get all apps
		 */
		$apps  = $this->_getAllApps();

		// we'll distribute the apps from the response between the following arrays
		$installedApps = array();
		$freeApps = array();
		$paidApps = array();

		if ($apps) {
			foreach ($apps as $id => $app) {

				// Check if this App is available as Yii module/plugin here
				$plugin_name =  ucfirst($app['internal_codename']) . "App";
				if (! PluginManager::isModulePlugin($plugin_name) ) {
					continue;
				}

				if ($app['is_installed'] == 1) {
					$installedApps[] = $app;
				}
				else if ($app['market_type'] == 'free') {
					$freeApps[] = $app;
				} else {
					$paidApps[] = $app;
				}
			}
		}

		$html .= $this->renderPartial('_apps_grid', array(
			'apps'=>$installedApps,
			'coverTile'=>$this->renderPartial('_cover_tile', array(
					'bgCss' => 'bg-color-orange',
					'title' => Yii::t('apps', 'My<br> apps'),
					'description' => Yii::t('apps', 'Your apps list.')
				), true),
			'backCoverTile'=> (empty($installedApps)) ? $this->renderPartial('_no_installed_apps', array(), true) : ''
		), true);

		$html .= $this->renderPartial('_apps_grid', array(
			'apps'=>$freeApps,
			'coverTile'=>$this->renderPartial('_cover_tile', array(
					'bgCss' => 'bg-color-blue',
					'title' => Yii::t('apps', 'Free apps'),
					'description' => Yii::t('apps', 'Browse our <strong>FREE</strong> apps to extend your Docebo Cloud'),
					'icon' => 'grid'
				), true)
		), true);

		$html .= $this->renderPartial('_apps_grid', array(
			'apps'=>$paidApps,
			'coverTile'=>$this->renderPartial('_cover_tile', array(
					'bgCss' => 'bg-color-green',
					'title' => Yii::t('apps', 'Paid apps'),
					'description' => Yii::t('apps', 'Browse our <strong>PAID</strong> apps to extend your Docebo Cloud'),
					'icon' => 'cart'
				), true)
		), true);

		echo CJSON::encode(array(
			'html'  => $html,
		));
		Yii::app()->end();
	}

	/*
	 * These will be displayed in the left sidebar in the Apps page.
	 * Note that the order here is important! It will be preserved during display.
	 */
	private function _getAppCategoryTranslations(){
		return array(
			'docebo_additional_features' => Yii::t('app', 'Docebo Additional Features'),
			'third_party_integrations' => Yii::t('app', 'Third party integrations'),
			'web_conferencing' => Yii::t('menu_course', '_TELESKILL_ROOM'),
			'single_sing_on' => Yii::t('app', 'Single Sign On'),
		);
	}

	public function actionGetAppCategories(){

		$categoryTranslations = $this->_getAppCategoryTranslations();

		// [category]=>[css class] pair. The CSS class will be
		// applied to the <a> link of the category in the Sidebarred widget
		// E.g. 'single_sing_on'=>'three-dots'
		// will apply the following CSS to the category 'single_sign_on':
		// .sidebarred .sidebar ul li a.three-dots span{}
		// See shared.css for the available classes
		$categoryIcons = array(
			'single_sing_on' => 'lock',
			'docebo_additional_features' => 'bullet-list',
			'third_party_integrations' => 'chain',
			'web_conferencing' => 'webcam',
		);

		$categories = array();

		// Add 'My apps' as the first category
		$categories[Yii::t('apps', 'My<br> apps')] = CHtml::link('<span></span>'.Yii::t('apps', 'My<br> apps'), '#myapps', array(
			'data-loaded' => 0,
			'class'=>'myapps category tiles myappsitem',
			'data-tab' => 'myapps',
			'data-url' => 'app/getApps&action=myapps',
		));

		foreach($categoryTranslations as $key=>$categoryName){

			$categories[$categoryName] = CHtml::link('<span></span>'.$categoryName, '#'. $key, array(
				'id' => $key.'_tab_btn',
				'data-loaded' => 0,
				'class'=>'myappsitem category '.$key . ($categoryIcons[$key] ? ' '.$categoryIcons[$key] : ''),
				'data-tab' => $key,
				'data-url' => 'app/getApps&action=category&catName='.trim($key),
			));
		}

		/*$categories[Yii::t('userlimit', 'Help Desk')] = CHtml::link('<span></span>'.Yii::t('userlimit', 'Help Desk'), '#fullpage-helpdesk', array(
			'data-loaded' => 0,
			'class'=>'fullpage-helpdesk category helpdesk myappsitem',
			'data-tab' => 'fullpage-helpdesk',
			'data-url' => 'app/getFullpageApp&app=helpdesk',
		));

		$categories[Yii::t('apps', 'Enterprise Cloud Solution')] = CHtml::link('<span></span>'.Yii::t('apps', 'Enterprise Cloud Solution'), '#fullpage-ecs', array(
			'data-loaded' => 0,
			'class'=>'fullpage-ecs category ecs myappsitem',
			'data-tab' => 'fullpage-ecs',
			'data-url' => 'app/getFullpageApp&app=ecs',
			'data-bootstro-id' => "bootstroNewAppsDesign",
		));*/

		echo CJSON::encode($categories);
		Yii::app()->end();
	}

	/**
	 * Return content/info for a special app that has a standalone category-like page
	 * (e.g. Help Desk app or the ECS app)
	 *
	 * @param string $app
	 */
	public function actionGetFullpageApp($app = null){
		$apps  = $this->_getAllApps();
		$appByGroup = array(); // sorted by price
		if($apps){
			foreach($apps as $singleApp){
				if($singleApp['app_group']){
					// Exclude apps without a group

					if(!isset($appByGroup[$singleApp['app_group']])){
						$appByGroup[$singleApp['app_group']] = array();
					}

					// Add this app to its group
					// Use the price as array key so we can easily sort the array by price later
					$appByGroup[$singleApp['app_group']][$singleApp['app_id']] = $singleApp;
				}
			}
		}

		// Sort the apps in each group by price
		foreach($appByGroup as $group => &$appsInGroup){
			ksort($appsInGroup);
		}

		switch($app){
//			case 'helpdesk':
//				$helpDeskAppsSorted = isset($appByGroup['helpdesk']) ? $appByGroup['helpdesk'] : array();
//
//				if(count($helpDeskAppsSorted) < 3){
//					echo CJSON::encode(array(
//						'html'  => 'The helpdesk app must have at least 3 levels'
//					));
//					Yii::app()->end();
//				}
//
//				$helpDeskSilver = array_slice($helpDeskAppsSorted, 0, 1, true);
//				$helpDeskSilver = reset($helpDeskSilver);
//
//				$helpDeskGold = array_slice($helpDeskAppsSorted, 1, 1, true);
//				$helpDeskGold = reset($helpDeskGold);
//
//				$helpDeskPlatinum = array_slice($helpDeskAppsSorted, 2, 1, true);
//				$helpDeskPlatinum = reset($helpDeskPlatinum);
//

lms/protected/views/app/_acceptECommerceShopifyInstPolicy.php
<?php
/* @var $this AppController */

/* @var bool $message */
/* @var bool $activatedApplication */

?>

<!-- Consumed by Dialog2, used as Dialog Title -->
<h1><?= Yii::t('shopify', 'Activating') . ' ' . $activatedApplication ?></h1>

<?= $message ?>

<div class="checkbox" style="margin-top: 10px">
	<?=CHtml::checkBox('instPolicy', false, array(
		'id' => 'instPolicy',
		'value' => false,
		'class' => 'instPolicy'
	));?>
	<?=CHtml::label(Yii::t('shopify', 'Yes, I want to proceed'), 'instPolicy', array(
		'style' => 'display: inline-block;'
	)); ?>
</div>

<br />
<div class="row-fluid right" style="text-align: right">
	<?= CHtml::button(Yii::t('shopify', 'CONFIRM'), array(
		'class' => 'btn btn-docebo green big',
		'name' => 'submit',
		'onclick' => "if ($('.instPolicy')[$('.instPolicy').length - 1].parentNode.childNodes[1].checked) { confirm() }",
	)); ?>
	<?= CHtml::button(Yii::t('shopify', 'CLOSE'), array(
		'class' => 'btn btn-docebo black big',
		'name' => 'cancel',
		'onclick' => "$('.modal').hide(); $('.modal-backdrop').hide(); ",
	)); ?>
</div>

<script>
	$('.modal-footer').hide();
	$('.instPolicy').styler();

	function confirm() {

		$.ajax({
			url: "index.php?r=app/axConfirmInstall&id=<?= $appId ?>&type=buy&confirmedECommerceShopifyInstPolicy=1"
		})
		.done(function( html ) {
				$('.modal-body')[$('.modal-body').length - 1].innerHTML = html;
				var scriptStartIndex = html.indexOf('script');
				eval(html.substr(scriptStartIndex + 7, html.length - 9 - scriptStartIndex - 7));

		});
	}
</script>

lms/protected/views/app/_app_details.php
<?php
/* @var $this AppController */

/* @var array $app */
/* @var array $lang */
/* @var bool $hasToContactResellerToInstall */
/* @var bool $isInTrialPeriod */

$_currency = '';
switch ($app['pricing']['currency']) {
	case 'usd': $_currency = '&dollar;'; break;
	case 'eur':
	default: $_currency = '&euro;'; break;
}

$isEnterprise = $app['is_enterprise']; // Is this Cloud Enterprise App?

// If the LMS subscription plan is higher than 500 users
$planIsGood = (!$isInTrialPeriod && $isEnterprise && Settings::get('max_users', 0) >= 500);
?>

<!-- Consumed by Dialog2, used as Dialog Title -->
<h1><?= $lang['title'] ?></h1>

<div class="app-details-dialog">
	<div class="pull-left thumb-area">
		<div class="app-title"><?= $lang['title'] ?></div>

		<?php
		// Try to get the app's image from the collection (Why do we have an array here?)
		$appImage = false;
		if(is_array($app['image'])){
			$imgUrls = array_values($app['image']);
			$appImage = $imgUrls[0];
		}else{
			$appImage = $app['image'];
		}
		?>
		<?php if($appImage): ?>
			<img alt="<?=$lang['title']?>" class="app-image" src="<?=$appImage?>">
		<?php endif; ?>


		<?php if($isFree): ?>
			<p><a href="<?= Yii::app()->createUrl('app/axConfirmInstall', array('id' => $app['app_id'], 'type' => 'install')) ?>" class="ajax btn-docebo blue full big text-center"><?= Yii::t('apps', 'Installnow') ?></a></p>
		<?php else: ?>
			<?php if($useContactus): ?>
				<?php if($enableUserBilling == 'on'): ?>
					<?php if(strtolower($app['internal_codename']) != 'salesforce'){ ?>
						<p class="payment-cycle">
							<?= Yii::t('app', 'Recurring {cycle} by <b>{pay_method}</b>', array(
								'{cycle}' => $cycle=='MONTH' ? 'Monthly' : 'Yearly',
								'{pay_method}' => $app['lms_payment_method']=='credit_card' ? Yii::t('order', 'Credit Card') : Yii::t('order', 'Wire transfer'),
							)); ?>
						</p>
					<?php } ?>
					<div class="contact-us-btn-area">
						<p><a class="contact-us-links btn-docebo blue big full text-center" href="javascript:;"><?=Yii::t('apps', 'Contact Us Now')?></a></p>
					</div>
				<?php else: ?>
					<?php if($isReseller): ?>
						<p class="payment-cycle">
							<?= Yii::t('app', 'Recurring {cycle} by <b>{pay_method}</b>', array(
								'{cycle}' => $cycle=='MONTH' ? 'Monthly' : 'Yearly',
								'{pay_method}' => $app['lms_payment_method']=='credit_card' ? Yii::t('order', 'Credit Card') : Yii::t('order', 'Wire transfer'),
							)); ?>
						</p>
						<div class="contact-us-btn-area">
							<p><a class="contact-us-links btn-docebo blue big full text-center" href="javascript:;"><?=Yii::t('apps', 'Contact Us Now')?></a></p>
						</div>
					<?php else: ?>
						<div class="discover-more">
							<p><?= Yii::t('app', '<strong>Contact Your Docebo Partner / Reseller</strong> for more information') ?></p>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			<?php else: ?>
				<?php if($isInTrialPeriod): ?>
					<div class="discover-more">
					<p class="dimmed"><?= Yii::t('apps', '{currency} {price} + VAT', array(
							// A hacky way to reuse a old string/i18n:
							'{currency}'=>'<span class="price">'.$_currency,
							'{price}'=>$app['pricing']['price'].'</span>',
							'<strong>'=>'',
							'</strong>'=>'',
						))?>/<?= ($app['market_type']=='subscription') ? strtolower($cycle) : ucwords(strtolower('ONE TIME PAYMENT')) ?></p>
					<?php if(!$app['is_enterprise']): ?>
						<p class="free-trial-days">
							<?=Yii::t('standard', '{days}-day Free Trial', array('{days}'=>Docebo::getTrialRemainingDays()));?>
						</p>
					<?php endif; ?>
						</div>
					<p><a href="<?= Yii::app()->createUrl('app/axConfirmInstall', array('id' => $app['app_id'], 'type' => 'trial')) ?>" class="ajax btn-docebo orange full big text-center"><?= Yii::t('apps', 'Startfreetrial') ?></a></p>
				<?php else: ?>
					<?php if(!$app['free_on_premium'] || !$isECSInstallation): ?>
						<?php if($enableUserBilling == 'on'): ?>
							<?php if($app['lms_payment_method'] == 'credit_card'): ?>
								<p class="payment-cycle">
									<?= Yii::t('app', 'Recurring {cycle} by <b>{pay_method}</b>', array(
										'{cycle}' => $cycle=='MONTH' ? 'Monthly' : 'Yearly',
										'{pay_method}' => $app['lms_payment_method']=='credit_card' ? Yii::t('order', 'Credit Card') : Yii::t('order', 'Wire transfer'),
									)); ?>
								</p>
								<div class="price-holder">
									<?= Yii::t('apps', '<span class="price">{currency} {price}</span> + VAT', array('{currency}'=>$_currency,'{price}'=>$app['pricing']['price'])) ?>/<?= ($app['market_type']=='subscription') ? strtolower($cycle) : ucwords(strtolower('ONE TIME PAYMENT')) ?>
								</div>
								<p><a href="<?=Yii::app()->createUrl('app/axConfirmInstall', array('id' => $app['app_id'], 'type' => 'buy')) ?>" class="ajax btn-docebo green full big text-center" data-dialog-class="wider"><?= Yii::t('userlimit', 'Buy now') ?></a></p>
							<?php else: ?>
								<div class="discover-more">
									<p class="wirecard-notice">
										<?=Yii::t('apps', 'To buy this app with your plan you must <span>contact your sales representative</span>')?>
									</p>
								</div>
								<div class="contact-us-btn-area">
									<p><a class="contact-us-links btn-docebo blue big full text-center" href="javascript:;"><?=Yii::t('apps', 'Contact Us Now')?></a></p>
								</div>
							<?php endif; ?>
						<?php else: ?>
							<?php if($isReseller): ?>
								<p class="payment-cycle">
									<?= Yii::t('app', 'Recurring {cycle} by <b>{pay_method}</b>', array(
										'{cycle}' => $cycle=='MONTH' ? 'Monthly' : 'Yearly',
										'{pay_method}' => $app['lms_payment_method']=='credit_card' ? Yii::t('order', 'Credit Card') : Yii::t('order', 'Wire transfer'),
									)); ?>
								</p>
								<div class="contact-us-btn-area">
									<p><a class="contact-us-links btn-docebo blue big full text-center" href="javascript:;"><?=Yii::t('apps', 'Contact Us Now')?></a></p>
								</div>
							<?php else: ?>
								<div class="discover-more">
									<p><?= Yii::t('app', '<strong>Contact Your Docebo Partner / Reseller</strong> for more information') ?></p>
								</div>
							<?php endif; ?>
						<?php endif; ?>
					<?php else: ?>
						<p><a href="<?= Yii::app()->createUrl('app/axConfirmInstall', array('id' => $app['app_id'], 'type' => 'install')) ?>" class="ajax btn-docebo blue full big text-center"><?= Yii::t('apps', 'Installnow') ?></a></p>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>
		<?php endif; ?>
		</div>
		<div class="description-holder <?=$isEnterprise ? 'enterprise' : ''?>">

			<?php if($isEnterprise
				// Only show this block if the Enterprise app is NOT in "pending activation" state
				&& (!isset($app['pending_enterprise']) || !$app['pending_enterprise'])): ?>
				<div class="cloud-enterprise-warning">
					<img class="warning pull-left" src="<?=Yii::app()->theme->baseUrl?>/images/warning-orange.png" alt="" />
					<div class="warning-text">
						<?php if(!$planIsGood): ?>
							<h4><?=Yii::t('app', 'You must have a 500 users or more subscription in order to activate this app.')?></h4>
						<?php endif; ?>

						<p><?=Yii::t('app', 'Once activated, this app <b>will be permanently linked to your plan</b> and <b>you won’t be able to cancel it</b> unless you cancel your 500 users or more  subscription.')?></p>
					</div>
				</div>
			<?php endif; ?>

			<?php if(!$isEnterprise): ?>
				<div class="app-description-header"><?=Yii::t('standard', '_DESCRIPTION')?>:</div>
			<?php endif; ?>
			<div class="app-description">
				<?php if (!$isEnterprise) {

					if (!empty($install_detail['custom_desciption'])) echo $install_detail['custom_desciption'];
					else echo str_replace("\n", '<br>', str_replace("\t", '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $lang['extended_description']));

				} else { // Enterprise app gets different description ?>
					<p><?= str_replace("\n", '<br>', str_replace("\t", '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $lang['extended_description'])) ?></p>

					<div class="row-fluid smaller-height-hack">
						<div class="span6">
							<h4><?=Yii::t('apps', 'With this app you will get:')?></h4>

							<ul class="features">
								<li><span></span><?=Yii::t('apps', '<b>Gold</b> Help Desk')?></li>
								<li><span></span><?=Yii::t('apps', '<b>Isolated Cloud</b> LMS Instance')?></li>
								<li><span></span><?=Yii::t('apps', '<b>Dedicated</b> Auto Scalable Infrastructure')?></li>
								<li><span></span><?=Yii::t('apps', 'Minor upgrades and updates are <b>auto provisioned</b> and <b>automatically deployed</b>')?></li>
								<li><span></span><?=Yii::t('apps', 'Migration to major versions are <b>agreed</b> upon and <b>scheduled</b> with customer')?></li>
								<li><span></span><?=Yii::t('apps', '<b>Fully open to custom features development</b>')?></li>
							</ul>
						</div>
						<div class="span6">
							<h4><?=Yii::t('apps', 'Additional apps Coming for free:')?></h4>

							<ul class="features">
								<li><span></span><?=Yii::t('app', 'custom_domain')?></li>
								<li><span></span><?=Yii::t('apps', 'Custom Domain HTTPs')?></li>
								<li><span></span><?=Yii::t('app', 'ecommerce')?></li>
								<li><span></span><?=Yii::t('templatemanager', 'White Label')?></li>
							</ul>

							<h4><?=Yii::t('apps', 'Uptime')?></h4>

							<ul class="features">
								<li><span></span><?=Yii::t('apps', '99.89%')?></li>
							</ul>
						</div>
					</div>

					<?php if(isset($app['pending_enterprise']) && $app['pending_enterprise']): // Already installed ?>
						<div class="enterprise-pending">
							<div class="pull-left green-check">
								<img alt="" src="<?=Yii::app()->theme->baseUrl?>/images/green-check-circled.png" />
							</div>
							<h3><?=Yii::t('apps', 'Your activation request is currently being processed')?></h3>
							<p><?=Yii::t('apps', 'You will be notified as soon as this app is active')?></p>
						</div>
					<?php endif; ?>
				<?php } //endif ?>
			</div>
		</div>
	</div>

	<div class="clearfix"></div>

	<script type="text/javascript">
		$(function(){
			
			$(document).on("click", ".modal-body.opened .contact-us-links", function(){
				$(this).closest(".modal-body").dialog2("close");
			});
			
			
			$('.app-details-dialog a.disabled').click(function(e){
				e.preventDefault();
				e.stopPropagation();
			});
		})
	</script>

lms/protected/views/app/_app_installed.php
<?php
/* @var $title string */
?>

<h1><?= $title ?></h1>

<?php if($success): ?>

<p><?= Yii::t('apps', 'Your app has been added to <strong>MY APPS</strong>.') ?> <i class="icon-ok"></i></p>

<?php else: ?>

	<p><?= Yii::t('apps', 'Error') ?> <i class="icon-minus-sign"></i></p>
	<br>

	<?php
	if(Yii::app()->user->hasFlash('error')):
		?>

		<p><?= Yii::app()->user->getFlash('error') ?></p>

		<?php

	endif;
	?>

<?php endif ?>

<a href="<?= Yii::app()->createUrl('app/index') ?>" class="btn btn-docebo green big pull-right span2"><?= Yii::t('apps', 'Go to my apps') ?></a>


<script type="text/javascript">
	$(document).delegate('.modal', 'dialog2.closed', function(){
		var e = $(this);
		if(console) {
			console.log(AppsGrid);
		}
		AppsGrid.refresh();
	});
</script>

lms/protected/views/app/_app_reactivated.php
<?php
/* @var $title string */
?>

<h1><?= $title ?></h1>

<p><?= Yii::t('apps', 'Your app has been reactivated.') ?> <i class="icon-ok"></i></p>

<a href="<?= Yii::app()->createUrl('app/index') ?>" class="btn btn-docebo green big pull-right span2"><?= Yii::t('apps', 'Go to my apps') ?></a>


<script type="text/javascript">
	$(document).delegate('.modal', 'dialog2.closed', function(){
		var e = $(this);
		if(console) {
			console.log(AppsGrid);
		}

		AppsGrid.refresh();
	});
</script>

lms/protected/views/app/_app_removed.php
<?php
/* @var $title string */
?>

<h1><?= $title ?></h1>

<?php if($success): ?>

<p><?= Yii::t('apps', 'Your app has been removed from <strong>MY APPS</strong>.') ?> <i class="icon-ok"></i></p>

<?php else: ?>

	<p><?= Yii::t('apps', 'Error') ?> <i class="icon-minus-sign"></i></p>
	<br>

	<?php
		if(Yii::app()->user->hasFlash('error')):
			?>

			<p><?= Yii::app()->user->getFlash('error') ?></p>

			<?php

		endif;
	?>

<?php endif ?>

<a href="<?= Yii::app()->createUrl('app/index') ?>" class="btn btn-docebo green big pull-right span2"><?= Yii::t('apps', 'Go to my apps') ?></a>


<script type="text/javascript">
	$(document).delegate('.modal', 'dialog2.closed', function(){
		var e = $(this);
		if(console) {
			console.log(AppsGrid);
		}

		AppsGrid.refresh();
	});
</script>

lms/protected/views/app/_app_template.php
<?php
/**
 * Created by PhpStorm.
 * User: Georgi
 * Date: 10.11.2015 г.
 * Time: 12:08
 */

$this->widget('common.widgets.AppWidget', array(
    'app' => $app,
    'isECSInstallation' => $isECSInstallation
));
?>

lms/protected/views/app/_apps_grid.php
<?php
/* @var $this AppController */

/* @var array $apps */
/* @var string $coverTile */
/* @var string $backCoverTile */

	$this->widget('common.widgets.AppsGrid', array('apps' => $apps, 'coverTile' => $coverTile, 'backCoverTile' => $backCoverTile));
?>